/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "receiver_SPI.v:14.1-159.10" *)
module receiver_SPI(clk, rst, CPH, CKP, MOSI, data_in, SS, SCK, MISO);
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire _000_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire _001_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [6:0] _002_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [15:0] _003_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire _004_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [6:0] _005_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [15:0] _006_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [2:0] _007_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire _008_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [6:0] _009_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [15:0] _010_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [2:0] _011_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire _012_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [6:0] _013_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [15:0] _014_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [2:0] _015_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire _016_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [6:0] _017_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [15:0] _018_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire _019_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [6:0] _020_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [15:0] _021_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [2:0] _022_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [2:0] _023_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire _024_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [6:0] _025_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [15:0] _026_;
  (* src = "receiver_SPI.v:75.5-157.8" *)
  wire [2:0] _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire [7:0] _075_;
  wire [3:0] _076_;
  wire [1:0] _077_;
  wire [2:0] _078_;
  wire [1:0] _079_;
  wire [2:0] _080_;
  wire [1:0] _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire [15:0] _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  (* src = "receiver_SPI.v:126.29-126.53" *)
  wire _089_;
  (* src = "receiver_SPI.v:106.21-106.33" *)
  wire _090_;
  (* src = "receiver_SPI.v:121.21-121.32" *)
  wire _091_;
  (* src = "receiver_SPI.v:126.29-126.71" *)
  wire _092_;
  (* src = "receiver_SPI.v:131.21-131.32" *)
  wire _093_;
  (* src = "receiver_SPI.v:141.21-141.31" *)
  wire _094_;
  (* src = "receiver_SPI.v:106.21-106.25" *)
  wire _095_;
  (* src = "receiver_SPI.v:106.29-106.33" *)
  wire _096_;
  (* src = "receiver_SPI.v:53.26-53.39" *)
  wire _097_;
  (* src = "receiver_SPI.v:54.42-54.46" *)
  wire _098_;
  (* src = "receiver_SPI.v:126.57-126.71" *)
  wire _099_;
  wire [6:0] _100_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [8:0] _101_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [8:0] _102_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _103_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [2:0] _104_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [13:0] _105_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [13:0] _106_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [31:0] _107_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [31:0] _108_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [15:0] _109_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "6" *)
  wire [31:0] _110_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _111_;
  (* force_downto = 32'd1 *)
  (* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "7" *)
  wire [31:0] _112_;
  (* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _113_;
  (* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _114_;
  (* src = "receiver_SPI.v:30.26-30.29" *)
  input CKP;
  wire CKP;
  (* src = "receiver_SPI.v:30.21-30.24" *)
  input CPH;
  wire CPH;
  (* src = "receiver_SPI.v:34.16-34.20" *)
  output MISO;
  reg MISO;
  (* src = "receiver_SPI.v:30.31-30.35" *)
  input MOSI;
  wire MOSI;
  (* src = "receiver_SPI.v:30.41-30.44" *)
  input SCK;
  wire SCK;
  (* src = "receiver_SPI.v:30.37-30.39" *)
  input SS;
  wire SS;
  (* src = "receiver_SPI.v:30.11-30.14" *)
  input clk;
  wire clk;
  (* src = "receiver_SPI.v:46.15-46.24" *)
  reg [6:0] count_bit;
  (* src = "receiver_SPI.v:31.18-31.25" *)
  input [15:0] data_in;
  wire [15:0] data_in;
  (* src = "receiver_SPI.v:48.16-48.26" *)
  reg [15:0] inter_data;
  (* src = "receiver_SPI.v:50.10-50.21" *)
  wire negedge_sck;
  (* src = "receiver_SPI.v:46.26-46.38" *)
  wire [6:0] nx_count_bit;
  (* src = "receiver_SPI.v:48.28-48.41" *)
  wire [15:0] nx_inter_data;
  (* src = "receiver_SPI.v:45.22-45.30" *)
  wire [2:0] nx_state;
  (* src = "receiver_SPI.v:49.10-49.21" *)
  wire posedge_sck;
  (* src = "receiver_SPI.v:30.16-30.19" *)
  input rst;
  wire rst;
  (* src = "receiver_SPI.v:52.9-52.21" *)
  reg sck_anterior;
  (* src = "receiver_SPI.v:45.15-45.20" *)
  reg [2:0] state;
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[0] <= 1'h0;
    else if (_028_) inter_data[0] <= nx_inter_data[0];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[1] <= 1'h0;
    else if (_028_) inter_data[1] <= nx_inter_data[1];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[2] <= 1'h0;
    else if (_028_) inter_data[2] <= nx_inter_data[2];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[3] <= 1'h0;
    else if (_028_) inter_data[3] <= nx_inter_data[3];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[4] <= 1'h0;
    else if (_028_) inter_data[4] <= nx_inter_data[4];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[5] <= 1'h0;
    else if (_028_) inter_data[5] <= nx_inter_data[5];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[6] <= 1'h0;
    else if (_028_) inter_data[6] <= nx_inter_data[6];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[7] <= 1'h0;
    else if (_028_) inter_data[7] <= nx_inter_data[7];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[8] <= 1'h0;
    else if (_028_) inter_data[8] <= nx_inter_data[8];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[9] <= 1'h0;
    else if (_028_) inter_data[9] <= nx_inter_data[9];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[10] <= 1'h0;
    else if (_028_) inter_data[10] <= nx_inter_data[10];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[11] <= 1'h0;
    else if (_028_) inter_data[11] <= nx_inter_data[11];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[12] <= 1'h0;
    else if (_028_) inter_data[12] <= nx_inter_data[12];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[13] <= 1'h0;
    else if (_028_) inter_data[13] <= nx_inter_data[13];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[14] <= 1'h0;
    else if (_028_) inter_data[14] <= nx_inter_data[14];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) inter_data[15] <= 1'h0;
    else if (_028_) inter_data[15] <= nx_inter_data[15];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) count_bit[0] <= 1'h0;
    else if (_031_) count_bit[0] <= nx_count_bit[0];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) count_bit[1] <= 1'h0;
    else if (_031_) count_bit[1] <= nx_count_bit[1];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) count_bit[2] <= 1'h0;
    else if (_031_) count_bit[2] <= nx_count_bit[2];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) count_bit[3] <= 1'h0;
    else if (_031_) count_bit[3] <= nx_count_bit[3];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) count_bit[4] <= 1'h0;
    else if (_031_) count_bit[4] <= nx_count_bit[4];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) count_bit[5] <= 1'h0;
    else if (_031_) count_bit[5] <= nx_count_bit[5];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) count_bit[6] <= 1'h0;
    else if (_031_) count_bit[6] <= nx_count_bit[6];
  (* src = "receiver_SPI.v:75.5-157.8" *)
  always @*
    if (!_059_) MISO = _000_;
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) state[0] <= 1'h0;
    else if (_032_) state[0] <= nx_state[0];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) state[1] <= 1'h0;
    else if (_032_) state[1] <= nx_state[1];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) state[2] <= 1'h0;
    else if (_032_) state[2] <= nx_state[2];
  (* src = "receiver_SPI.v:57.5-72.8" *)
  always @(posedge clk)
    if (!rst) sck_anterior <= 1'h0;
    else sck_anterior <= SCK;
  assign _068_ = ~state[0];
  assign _069_ = ~state[1];
  assign _111_[0] = ~count_bit[0];
  assign _071_ = ~_017_[5];
  assign _072_ = ~_017_[4];
  assign _073_ = ~SS;
  assign _030_ = _028_ | _103_[2];
  assign _031_ = _103_[0] | _103_[2];
  assign _032_ = _030_ & _029_;
  assign _052_ = _064_ |(* src = "receiver_SPI.v:75.5-157.8" *)  _063_;
  assign _029_ = _073_ | _070_;
  assign _059_ = _067_ |(* src = "receiver_SPI.v:75.5-157.8" *)  _033_;
  assign _057_ = _065_ |(* src = "receiver_SPI.v:75.5-157.8" *)  _066_;
  assign _047_ = _061_ |(* src = "receiver_SPI.v:75.5-157.8" *)  _062_;
  assign _042_ = _060_ |(* src = "receiver_SPI.v:75.5-157.8" *)  _037_;
  assign _074_ = state[0] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *)  _069_;
  assign _033_ = _074_ |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *)  state[2];
  assign _075_[0] = _085_[0] |(* src = "receiver_SPI.v:146.29-146.53" *)  _085_[1];
  assign _075_[1] = _085_[2] |(* src = "receiver_SPI.v:146.29-146.53" *)  _085_[3];
  assign _075_[2] = _085_[4] |(* src = "receiver_SPI.v:146.29-146.53" *)  _085_[5];
  assign _075_[3] = _085_[6] |(* src = "receiver_SPI.v:146.29-146.53" *)  _085_[7];
  assign _075_[4] = _085_[8] |(* src = "receiver_SPI.v:146.29-146.53" *)  _085_[9];
  assign _075_[5] = _085_[10] |(* src = "receiver_SPI.v:146.29-146.53" *)  _085_[11];
  assign _075_[6] = _085_[12] |(* src = "receiver_SPI.v:146.29-146.53" *)  _085_[13];
  assign _075_[7] = _085_[14] |(* src = "receiver_SPI.v:146.29-146.53" *)  _085_[15];
  assign _076_[0] = _075_[0] |(* src = "receiver_SPI.v:146.29-146.53" *)  _075_[1];
  assign _076_[1] = _075_[2] |(* src = "receiver_SPI.v:146.29-146.53" *)  _075_[3];
  assign _076_[2] = _075_[4] |(* src = "receiver_SPI.v:146.29-146.53" *)  _075_[5];
  assign _076_[3] = _075_[6] |(* src = "receiver_SPI.v:146.29-146.53" *)  _075_[7];
  assign _077_[0] = _076_[0] |(* src = "receiver_SPI.v:146.29-146.53" *)  _076_[1];
  assign _077_[1] = _076_[2] |(* src = "receiver_SPI.v:146.29-146.53" *)  _076_[3];
  assign _086_ = _077_[0] |(* src = "receiver_SPI.v:146.29-146.53" *)  _077_[1];
  assign _078_[0] = _111_[0] |(* src = "receiver_SPI.v:146.57-146.71" *)  count_bit[1];
  assign _078_[1] = count_bit[2] |(* src = "receiver_SPI.v:146.57-146.71" *)  count_bit[3];
  assign _078_[2] = count_bit[4] |(* src = "receiver_SPI.v:146.57-146.71" *)  count_bit[5];
  assign _079_[0] = _078_[0] |(* src = "receiver_SPI.v:146.57-146.71" *)  _078_[1];
  assign _079_[1] = _078_[2] |(* src = "receiver_SPI.v:146.57-146.71" *)  count_bit[6];
  assign _099_ = _079_[0] |(* src = "receiver_SPI.v:146.57-146.71" *)  _079_[1];
  assign _080_[0] = _017_[0] |(* src = "receiver_SPI.v:151.26-151.44" *)  _017_[1];
  assign _080_[1] = _017_[2] |(* src = "receiver_SPI.v:151.26-151.44" *)  _017_[3];
  assign _080_[2] = _072_ |(* src = "receiver_SPI.v:151.26-151.44" *)  _071_;
  assign _081_[0] = _080_[0] |(* src = "receiver_SPI.v:151.26-151.44" *)  _080_[1];
  assign _081_[1] = _080_[2] |(* src = "receiver_SPI.v:151.26-151.44" *)  _017_[6];
  assign _087_ = _081_[0] |(* src = "receiver_SPI.v:151.26-151.44" *)  _081_[1];
  assign _082_ = _068_ |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *)  state[1];
  assign _088_ = _082_ |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *)  state[2];
  assign _109_[14] = _108_[14] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[30];
  assign _109_[13] = _108_[13] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[29];
  assign _109_[15] = _108_[15] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[31];
  assign _104_[2] = _102_[2] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _102_[8];
  assign _083_ = _102_[1] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _102_[4];
  assign _104_[1] = _083_ |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _102_[8];
  assign _028_ = _103_[0] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _102_[4];
  assign _104_[0] = _102_[0] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _102_[6];
  assign _109_[1] = _108_[1] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[17];
  assign _109_[8] = _108_[8] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[24];
  assign _109_[11] = _108_[11] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[27];
  assign _109_[9] = _108_[9] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[25];
  assign _109_[10] = _108_[10] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[26];
  assign _109_[4] = _108_[4] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[20];
  assign _109_[0] = _108_[0] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[16];
  assign _109_[12] = _108_[12] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[28];
  assign _109_[7] = _108_[7] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[23];
  assign _109_[5] = _108_[5] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[21];
  assign _109_[6] = _108_[6] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[22];
  assign _109_[3] = _108_[3] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[19];
  assign _109_[2] = _108_[2] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _108_[18];
  assign _084_ = state[0] |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *)  state[1];
  assign _070_ = _084_ |(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *)  state[2];
  assign _095_ = ~(* src = "receiver_SPI.v:121.21-121.25" *) CKP;
  assign _098_ = ~(* src = "receiver_SPI.v:54.42-54.46" *) SCK;
  assign _097_ = ~(* src = "receiver_SPI.v:53.26-53.39" *) sck_anterior;
  assign _103_[2] = ~(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) _070_;
  assign _103_[0] = ~(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) _033_;
  assign _096_ = ~(* src = "receiver_SPI.v:131.28-131.32" *) CPH;
  assign _089_ = ~(* src = "receiver_SPI.v:146.29-146.53" *) _086_;
  assign _102_[4] = ~(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) _088_;
  assign negedge_sck = sck_anterior &(* src = "receiver_SPI.v:54.26-54.46" *)  _098_;
  assign posedge_sck = _097_ &(* src = "receiver_SPI.v:53.26-53.46" *)  SCK;
  assign _091_ = _095_ &(* src = "receiver_SPI.v:121.21-121.32" *)  CPH;
  assign _090_ = _095_ &(* src = "receiver_SPI.v:106.21-106.33" *)  _096_;
  assign _093_ = CKP &(* src = "receiver_SPI.v:131.21-131.32" *)  _096_;
  assign _094_ = CKP &(* src = "receiver_SPI.v:141.21-141.31" *)  CPH;
  assign _092_ = _089_ &(* src = "receiver_SPI.v:146.29-146.71" *)  _099_;
  assign _027_[0] = _087_ ? (* src = "receiver_SPI.v:151.26-151.44|receiver_SPI.v:151.22-151.65" *) _007_[0] : 1'h0;
  assign _027_[1] = _087_ ? (* src = "receiver_SPI.v:151.26-151.44|receiver_SPI.v:151.22-151.65" *) _007_[1] : 1'h0;
  assign _027_[2] = _087_ ? (* src = "receiver_SPI.v:151.26-151.44|receiver_SPI.v:151.22-151.65" *) _007_[2] : 1'h0;
  assign _024_ = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[0] : _016_;
  assign _023_[0] = _092_ ? (* src = "receiver_SPI.v:146.29-146.71|receiver_SPI.v:146.25-146.92" *) 1'h0 : _007_[0];
  assign _023_[1] = _092_ ? (* src = "receiver_SPI.v:146.29-146.71|receiver_SPI.v:146.25-146.92" *) 1'h0 : _007_[1];
  assign _023_[2] = _092_ ? (* src = "receiver_SPI.v:146.29-146.71|receiver_SPI.v:146.25-146.92" *) 1'h0 : _007_[2];
  assign _025_[0] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _111_[0] : _017_[0];
  assign _025_[1] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _112_[1] : _017_[1];
  assign _025_[2] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _112_[2] : _017_[2];
  assign _025_[3] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _112_[3] : _017_[3];
  assign _025_[4] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _112_[4] : _017_[4];
  assign _025_[5] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _112_[5] : _017_[5];
  assign _025_[6] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _112_[6] : _017_[6];
  assign _105_[0] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _025_[0] : _017_[0];
  assign _105_[1] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _025_[1] : _017_[1];
  assign _105_[2] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _025_[2] : _017_[2];
  assign _105_[3] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _025_[3] : _017_[3];
  assign _105_[4] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _025_[4] : _017_[4];
  assign _105_[5] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _025_[5] : _017_[5];
  assign _105_[6] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _025_[6] : _017_[6];
  assign _026_[0] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[1] : _018_[0];
  assign _026_[1] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[2] : _018_[1];
  assign _026_[2] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[3] : _018_[2];
  assign _026_[3] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[4] : _018_[3];
  assign _026_[4] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[5] : _018_[4];
  assign _026_[5] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[6] : _018_[5];
  assign _026_[6] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[7] : _018_[6];
  assign _026_[7] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[8] : _018_[7];
  assign _026_[8] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[9] : _018_[8];
  assign _026_[9] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[10] : _018_[9];
  assign _026_[10] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[11] : _018_[10];
  assign _026_[11] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[12] : _018_[11];
  assign _026_[12] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[13] : _018_[12];
  assign _026_[13] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[14] : _018_[13];
  assign _026_[14] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) inter_data[15] : _018_[14];
  assign _026_[15] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) MOSI : _018_[15];
  assign _021_[0] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[1] : _010_[0];
  assign _021_[1] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[2] : _010_[1];
  assign _021_[2] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[3] : _010_[2];
  assign _021_[3] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[4] : _010_[3];
  assign _021_[4] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[5] : _010_[4];
  assign _021_[5] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[6] : _010_[5];
  assign _021_[6] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[7] : _010_[6];
  assign _021_[7] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[8] : _010_[7];
  assign _021_[8] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[9] : _010_[8];
  assign _021_[9] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[10] : _010_[9];
  assign _021_[10] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[11] : _010_[10];
  assign _021_[11] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[12] : _010_[11];
  assign _021_[12] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[13] : _010_[12];
  assign _021_[13] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[14] : _010_[13];
  assign _021_[14] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[15] : _010_[14];
  assign _021_[15] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) MOSI : _010_[15];
  assign _014_[0] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[1] : _003_[0];
  assign _014_[1] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[2] : _003_[1];
  assign _014_[2] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[3] : _003_[2];
  assign _014_[3] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[4] : _003_[3];
  assign _014_[4] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[5] : _003_[4];
  assign _014_[5] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[6] : _003_[5];
  assign _014_[6] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[7] : _003_[6];
  assign _014_[7] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[8] : _003_[7];
  assign _014_[8] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[9] : _003_[8];
  assign _014_[9] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[10] : _003_[9];
  assign _014_[10] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[11] : _003_[10];
  assign _014_[11] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[12] : _003_[11];
  assign _014_[12] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[13] : _003_[12];
  assign _014_[13] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[14] : _003_[13];
  assign _014_[14] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[15] : _003_[14];
  assign _014_[15] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) MOSI : _003_[15];
  assign _101_[0] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _022_[0] : _027_[0];
  assign _101_[1] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _022_[1] : _027_[1];
  assign _101_[2] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _022_[2] : _027_[2];
  assign _016_ = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _019_ : _008_;
  assign _011_[0] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _015_[0] : state[0];
  assign _011_[1] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _015_[1] : state[1];
  assign _011_[2] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _015_[2] : state[2];
  assign _019_ = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) inter_data[0] : _008_;
  assign _100_[0] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _020_[0] : _009_[0];
  assign _100_[1] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _020_[1] : _009_[1];
  assign _100_[2] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _020_[2] : _009_[2];
  assign _100_[3] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _020_[3] : _009_[3];
  assign _100_[4] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _020_[4] : _009_[4];
  assign _100_[5] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _020_[5] : _009_[5];
  assign _100_[6] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _020_[6] : _009_[6];
  assign _013_[0] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _111_[0] : _002_[0];
  assign _013_[1] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _112_[1] : _002_[1];
  assign _013_[2] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _112_[2] : _002_[2];
  assign _013_[3] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _112_[3] : _002_[3];
  assign _013_[4] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _112_[4] : _002_[4];
  assign _013_[5] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _112_[5] : _002_[5];
  assign _013_[6] = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) _112_[6] : _002_[6];
  assign _107_[0] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[0] : _018_[0];
  assign _107_[1] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[1] : _018_[1];
  assign _107_[2] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[2] : _018_[2];
  assign _107_[3] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[3] : _018_[3];
  assign _107_[4] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[4] : _018_[4];
  assign _107_[5] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[5] : _018_[5];
  assign _107_[6] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[6] : _018_[6];
  assign _107_[7] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[7] : _018_[7];
  assign _107_[8] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[8] : _018_[8];
  assign _107_[9] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[9] : _018_[9];
  assign _107_[10] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[10] : _018_[10];
  assign _107_[11] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[11] : _018_[11];
  assign _107_[12] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[12] : _018_[12];
  assign _107_[13] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[13] : _018_[13];
  assign _107_[14] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[14] : _018_[14];
  assign _107_[15] = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _026_[15] : _018_[15];
  assign _018_[0] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[0] : _010_[0];
  assign _018_[1] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[1] : _010_[1];
  assign _018_[2] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[2] : _010_[2];
  assign _018_[3] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[3] : _010_[3];
  assign _018_[4] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[4] : _010_[4];
  assign _018_[5] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[5] : _010_[5];
  assign _018_[6] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[6] : _010_[6];
  assign _018_[7] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[7] : _010_[7];
  assign _018_[8] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[8] : _010_[8];
  assign _018_[9] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[9] : _010_[9];
  assign _018_[10] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[10] : _010_[10];
  assign _018_[11] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[11] : _010_[11];
  assign _018_[12] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[12] : _010_[12];
  assign _018_[13] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[13] : _010_[13];
  assign _018_[14] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[14] : _010_[14];
  assign _018_[15] = _093_ ? (* src = "receiver_SPI.v:131.21-131.32|receiver_SPI.v:131.17-137.20" *) _021_[15] : _010_[15];
  assign _015_[0] = _092_ ? (* src = "receiver_SPI.v:126.29-126.71|receiver_SPI.v:126.25-126.92" *) 1'h0 : state[0];
  assign _015_[1] = _092_ ? (* src = "receiver_SPI.v:126.29-126.71|receiver_SPI.v:126.25-126.92" *) 1'h0 : state[1];
  assign _015_[2] = _092_ ? (* src = "receiver_SPI.v:126.29-126.71|receiver_SPI.v:126.25-126.92" *) 1'h0 : state[2];
  assign _022_[0] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _023_[0] : _007_[0];
  assign _022_[1] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _023_[1] : _007_[1];
  assign _022_[2] = negedge_sck ? (* src = "receiver_SPI.v:142.25-142.36|receiver_SPI.v:142.21-147.24" *) _023_[2] : _007_[2];
  assign _017_[0] = _033_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) 1'hx : _100_[0];
  assign _017_[1] = _033_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) 1'hx : _100_[1];
  assign _017_[2] = _033_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) 1'hx : _100_[2];
  assign _017_[3] = _033_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) 1'hx : _100_[3];
  assign _017_[4] = _033_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) 1'hx : _100_[4];
  assign _017_[5] = _033_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) 1'hx : _100_[5];
  assign _017_[6] = _033_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16" *) 1'hx : _100_[6];
  assign _000_ = _094_ ? (* src = "receiver_SPI.v:141.21-141.31|receiver_SPI.v:141.17-151.65" *) _024_ : _016_;
  assign _020_[0] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) _111_[0] : _009_[0];
  assign _020_[1] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) _112_[1] : _009_[1];
  assign _020_[2] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) _112_[2] : _009_[2];
  assign _020_[3] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) _112_[3] : _009_[3];
  assign _020_[4] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) _112_[4] : _009_[4];
  assign _020_[5] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) _112_[5] : _009_[5];
  assign _020_[6] = posedge_sck ? (* src = "receiver_SPI.v:132.25-132.36|receiver_SPI.v:132.21-136.24" *) _112_[6] : _009_[6];
  assign _009_[0] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _013_[0] : _002_[0];
  assign _009_[1] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _013_[1] : _002_[1];
  assign _009_[2] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _013_[2] : _002_[2];
  assign _009_[3] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _013_[3] : _002_[3];
  assign _009_[4] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _013_[4] : _002_[4];
  assign _009_[5] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _013_[5] : _002_[5];
  assign _009_[6] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _013_[6] : _002_[6];
  assign _007_[0] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _011_[0] : state[0];
  assign _007_[1] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _011_[1] : state[1];
  assign _007_[2] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _011_[2] : state[2];
  assign _005_[0] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) _111_[0] : count_bit[0];
  assign _005_[1] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) _112_[1] : count_bit[1];
  assign _005_[2] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) _112_[2] : count_bit[2];
  assign _005_[3] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) _112_[3] : count_bit[3];
  assign _005_[4] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) _112_[4] : count_bit[4];
  assign _005_[5] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) _112_[5] : count_bit[5];
  assign _005_[6] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) _112_[6] : count_bit[6];
  assign _004_ = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[0] : MISO;
  assign _002_[0] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _005_[0] : count_bit[0];
  assign _002_[1] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _005_[1] : count_bit[1];
  assign _002_[2] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _005_[2] : count_bit[2];
  assign _002_[3] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _005_[3] : count_bit[3];
  assign _002_[4] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _005_[4] : count_bit[4];
  assign _002_[5] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _005_[5] : count_bit[5];
  assign _002_[6] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _005_[6] : count_bit[6];
  assign _008_ = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _012_ : _001_;
  assign _003_[0] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[0] : inter_data[0];
  assign _003_[1] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[1] : inter_data[1];
  assign _003_[2] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[2] : inter_data[2];
  assign _003_[3] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[3] : inter_data[3];
  assign _003_[4] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[4] : inter_data[4];
  assign _003_[5] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[5] : inter_data[5];
  assign _003_[6] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[6] : inter_data[6];
  assign _003_[7] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[7] : inter_data[7];
  assign _003_[8] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[8] : inter_data[8];
  assign _003_[9] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[9] : inter_data[9];
  assign _003_[10] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[10] : inter_data[10];
  assign _003_[11] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[11] : inter_data[11];
  assign _003_[12] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[12] : inter_data[12];
  assign _003_[13] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[13] : inter_data[13];
  assign _003_[14] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[14] : inter_data[14];
  assign _003_[15] = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _006_[15] : inter_data[15];
  assign _101_[6] = SS ? (* src = "receiver_SPI.v:90.21-90.24|receiver_SPI.v:90.17-90.43" *) 1'hx : 1'h1;
  assign _101_[8] = SS ? (* src = "receiver_SPI.v:90.21-90.24|receiver_SPI.v:90.17-90.43" *) 1'hx : 1'h0;
  assign _006_[0] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[1] : inter_data[0];
  assign _006_[1] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[2] : inter_data[1];
  assign _006_[2] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[3] : inter_data[2];
  assign _006_[3] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[4] : inter_data[3];
  assign _006_[4] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[5] : inter_data[4];
  assign _006_[5] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[6] : inter_data[5];
  assign _006_[6] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[7] : inter_data[6];
  assign _006_[7] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[8] : inter_data[7];
  assign _006_[8] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[9] : inter_data[8];
  assign _006_[9] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[10] : inter_data[9];
  assign _006_[10] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[11] : inter_data[10];
  assign _006_[11] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[12] : inter_data[11];
  assign _006_[12] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[13] : inter_data[12];
  assign _006_[13] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[14] : inter_data[13];
  assign _006_[14] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) inter_data[15] : inter_data[14];
  assign _006_[15] = posedge_sck ? (* src = "receiver_SPI.v:107.25-107.36|receiver_SPI.v:107.21-111.24" *) MOSI : inter_data[15];
  assign _010_[0] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[0] : _003_[0];
  assign _010_[1] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[1] : _003_[1];
  assign _010_[2] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[2] : _003_[2];
  assign _010_[3] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[3] : _003_[3];
  assign _010_[4] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[4] : _003_[4];
  assign _010_[5] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[5] : _003_[5];
  assign _010_[6] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[6] : _003_[6];
  assign _010_[7] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[7] : _003_[7];
  assign _010_[8] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[8] : _003_[8];
  assign _010_[9] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[9] : _003_[9];
  assign _010_[10] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[10] : _003_[10];
  assign _010_[11] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[11] : _003_[11];
  assign _010_[12] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[12] : _003_[12];
  assign _010_[13] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[13] : _003_[13];
  assign _010_[14] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[14] : _003_[14];
  assign _010_[15] = _091_ ? (* src = "receiver_SPI.v:121.21-121.32|receiver_SPI.v:121.17-128.20" *) _014_[15] : _003_[15];
  assign _001_ = _090_ ? (* src = "receiver_SPI.v:106.21-106.33|receiver_SPI.v:106.17-118.20" *) _004_ : MISO;
  assign _012_ = negedge_sck ? (* src = "receiver_SPI.v:122.25-122.36|receiver_SPI.v:122.21-127.24" *) inter_data[0] : _001_;
  assign nx_state[0] = _030_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _104_[0] : 1'hx;
  assign nx_state[1] = _030_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _104_[1] : 1'hx;
  assign nx_state[2] = _030_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _104_[2] : 1'hx;
  assign nx_inter_data[0] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[0] : 1'hx;
  assign nx_inter_data[1] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[1] : 1'hx;
  assign nx_inter_data[2] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[2] : 1'hx;
  assign nx_inter_data[3] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[3] : 1'hx;
  assign nx_inter_data[4] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[4] : 1'hx;
  assign nx_inter_data[5] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[5] : 1'hx;
  assign nx_inter_data[6] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[6] : 1'hx;
  assign nx_inter_data[7] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[7] : 1'hx;
  assign nx_inter_data[8] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[8] : 1'hx;
  assign nx_inter_data[9] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[9] : 1'hx;
  assign nx_inter_data[10] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[10] : 1'hx;
  assign nx_inter_data[11] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[11] : 1'hx;
  assign nx_inter_data[12] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[12] : 1'hx;
  assign nx_inter_data[13] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[13] : 1'hx;
  assign nx_inter_data[14] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[14] : 1'hx;
  assign nx_inter_data[15] = _028_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _109_[15] : 1'hx;
  assign nx_count_bit[0] = _031_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _106_[0] : 1'hx;
  assign nx_count_bit[1] = _031_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _106_[1] : 1'hx;
  assign nx_count_bit[2] = _031_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _106_[2] : 1'hx;
  assign nx_count_bit[3] = _031_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _106_[3] : 1'hx;
  assign nx_count_bit[4] = _031_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _106_[4] : 1'hx;
  assign nx_count_bit[5] = _031_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _106_[5] : 1'hx;
  assign nx_count_bit[6] = _031_ ? (* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _106_[6] : 1'hx;
  assign _039_ = ~(* src = "receiver_SPI.v:75.5-157.8" *) negedge_sck;
  assign _035_ = ~(* src = "receiver_SPI.v:75.5-157.8" *) _093_;
  assign _038_ = ~(* src = "receiver_SPI.v:75.5-157.8" *) posedge_sck;
  assign _037_ = ~(* src = "receiver_SPI.v:75.5-157.8" *) _090_;
  assign _036_ = ~(* src = "receiver_SPI.v:75.5-157.8" *) _091_;
  assign _034_ = ~(* src = "receiver_SPI.v:75.5-157.8" *) _094_;
  assign _054_ = _039_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _053_;
  assign _050_ = _093_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _049_;
  assign _063_ = _035_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _048_;
  assign _049_ = _038_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _048_;
  assign _053_ = _103_[0] &(* src = "receiver_SPI.v:75.5-157.8" *)  _052_;
  assign _065_ = _034_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _053_;
  assign _064_ = _093_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _051_;
  assign _051_ = _103_[0] &(* src = "receiver_SPI.v:75.5-157.8" *)  _050_;
  assign _055_ = _094_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _054_;
  assign _067_ = _103_[0] &(* src = "receiver_SPI.v:75.5-157.8" *)  _058_;
  assign _066_ = _094_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _056_;
  assign _056_ = _103_[0] &(* src = "receiver_SPI.v:75.5-157.8" *)  _055_;
  assign _058_ = _103_[0] &(* src = "receiver_SPI.v:75.5-157.8" *)  _057_;
  assign _048_ = _103_[0] &(* src = "receiver_SPI.v:75.5-157.8" *)  _047_;
  assign _061_ = _036_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _043_;
  assign _062_ = _091_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _046_;
  assign _046_ = _103_[0] &(* src = "receiver_SPI.v:75.5-157.8" *)  _045_;
  assign _045_ = _091_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _044_;
  assign _044_ = _039_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _043_;
  assign _060_ = _090_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _041_;
  assign _043_ = _103_[0] &(* src = "receiver_SPI.v:75.5-157.8" *)  _042_;
  assign _085_[0] = inter_data[1] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[0];
  assign _085_[1] = inter_data[2] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[1];
  assign _085_[2] = inter_data[3] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[2];
  assign _085_[3] = inter_data[4] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[3];
  assign _085_[4] = inter_data[5] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[4];
  assign _085_[5] = inter_data[6] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[5];
  assign _085_[6] = inter_data[7] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[6];
  assign _085_[7] = inter_data[8] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[7];
  assign _085_[8] = inter_data[9] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[8];
  assign _085_[9] = inter_data[10] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[9];
  assign _085_[10] = inter_data[11] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[10];
  assign _085_[11] = inter_data[12] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[11];
  assign _085_[12] = inter_data[13] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[12];
  assign _085_[13] = inter_data[14] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[13];
  assign _085_[14] = inter_data[15] ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[14];
  assign _085_[15] = MOSI ^(* src = "receiver_SPI.v:146.29-146.53" *)  data_in[15];
  assign _040_ = _090_ &(* src = "receiver_SPI.v:75.5-157.8" *)  _038_;
  assign _041_ = _103_[0] &(* src = "receiver_SPI.v:75.5-157.8" *)  _040_;
  assign _102_[6] = _101_[6] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[2];
  assign _102_[8] = _101_[8] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[2];
  assign _108_[16] = data_in[0] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[17] = data_in[1] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[18] = data_in[2] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[19] = data_in[3] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[20] = data_in[4] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[21] = data_in[5] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[22] = data_in[6] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[23] = data_in[7] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[24] = data_in[8] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[25] = data_in[9] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[26] = data_in[10] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[27] = data_in[11] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[28] = data_in[12] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[29] = data_in[13] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[30] = data_in[14] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[31] = data_in[15] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _102_[4];
  assign _108_[0] = _107_[0] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[1] = _107_[1] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[2] = _107_[2] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[3] = _107_[3] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[4] = _107_[4] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[5] = _107_[5] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[6] = _107_[6] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[7] = _107_[7] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[8] = _107_[8] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[9] = _107_[9] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[10] = _107_[10] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[11] = _107_[11] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[12] = _107_[12] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[13] = _107_[13] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[14] = _107_[14] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _108_[15] = _107_[15] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _102_[0] = _101_[0] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _102_[1] = _101_[1] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _102_[2] = _101_[2] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _106_[0] = _105_[0] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _106_[1] = _105_[1] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _106_[2] = _105_[2] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _106_[3] = _105_[3] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _106_[4] = _105_[4] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _106_[5] = _105_[5] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _106_[6] = _105_[6] &(* src = "receiver_SPI.v:0.0-0.0|receiver_SPI.v:87.9-155.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _103_[0];
  assign _112_[1] = count_bit[1] ^(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  count_bit[0];
  assign _112_[2] = count_bit[2] ^(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _110_[1];
  assign _112_[3] = count_bit[3] ^(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _110_[2];
  assign _112_[4] = count_bit[4] ^(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _110_[3];
  assign _112_[5] = count_bit[5] ^(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _110_[4];
  assign _112_[6] = count_bit[6] ^(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _110_[5];
  assign _110_[3] = _113_ &(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _110_[1];
  assign _114_ = count_bit[5] &(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count_bit[4];
  assign _113_ = count_bit[3] &(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count_bit[2];
  assign _110_[1] = count_bit[1] &(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  count_bit[0];
  assign _110_[5] = _114_ &(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _110_[3];
  assign _110_[2] = count_bit[2] &(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _110_[1];
  assign _110_[4] = count_bit[4] &(* src = "receiver_SPI.v:145.40-145.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _110_[3];
  assign { _101_[7], _101_[5:3] } = { _101_[8], 3'h2 };
  assign { _102_[7], _102_[5], _102_[3] } = { _102_[8], 2'h0 };
  assign _103_[1] = _102_[4];
  assign _105_[13:7] = 7'h00;
  assign _106_[13:7] = 7'h00;
  assign _107_[31:16] = data_in;
  assign { _110_[31:7], _110_[0] } = { 25'h0000000, count_bit[0] };
  assign _111_[31:1] = { 25'h0000000, count_bit[6:1] };
  assign { _112_[31:7], _112_[0] } = { 24'h000000, _110_[6], _111_[0] };
endmodule
