/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "transmitter_SPI.v:14.1-163.10" *)
module transmitter_SPI(clk, rst, CPH, CKP, MISO, strt, data_in, MOSI, SCK, CS);
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire _000_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire _001_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire _002_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire _003_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire _004_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire [6:0] _005_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire [15:0] _006_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire _007_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire [6:0] _008_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire [15:0] _009_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire _010_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire [6:0] _011_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire [15:0] _012_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire [2:0] _013_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire [2:0] _014_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  wire [2:0] _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire [7:0] _049_;
  wire [3:0] _050_;
  wire [1:0] _051_;
  wire [2:0] _052_;
  wire [1:0] _053_;
  wire [2:0] _054_;
  wire [1:0] _055_;
  wire _056_;
  wire _057_;
  wire [1:0] _058_;
  wire _059_;
  wire [1:0] _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire [15:0] _065_;
  wire [3:0] _066_;
  wire [2:0] _067_;
  wire _068_;
  wire _069_;
  (* src = "transmitter_SPI.v:144.29-144.53" *)
  wire _070_;
  (* src = "transmitter_SPI.v:56.26-56.39" *)
  wire _071_;
  (* src = "transmitter_SPI.v:57.42-57.46" *)
  wire _072_;
  (* src = "transmitter_SPI.v:144.57-144.71" *)
  wire _073_;
  wire [6:0] _074_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [8:0] _075_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [8:0] _076_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _077_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [2:0] _078_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [13:0] _079_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [13:0] _080_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [31:0] _081_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [31:0] _082_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [15:0] _083_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "6" *)
  wire [31:0] _084_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _085_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "7" *)
  wire [31:0] _086_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:70.29-70.39|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _087_;
  (* force_downto = 32'd1 *)
  (* src = "transmitter_SPI.v:70.29-70.39|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2" *)
  wire [31:0] _088_;
  (* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _089_;
  (* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _090_;
  (* src = "transmitter_SPI.v:31.26-31.29" *)
  input CKP;
  wire CKP;
  (* src = "transmitter_SPI.v:31.21-31.24" *)
  input CPH;
  wire CPH;
  (* src = "transmitter_SPI.v:35.16-35.18" *)
  output CS;
  reg CS;
  (* src = "transmitter_SPI.v:31.37-31.41" *)
  input MISO;
  wire MISO;
  (* src = "transmitter_SPI.v:35.20-35.24" *)
  output MOSI;
  reg MOSI;
  (* src = "transmitter_SPI.v:36.16-36.19" *)
  output SCK;
  reg SCK;
  (* src = "transmitter_SPI.v:31.11-31.14" *)
  input clk;
  wire clk;
  (* src = "transmitter_SPI.v:48.15-48.24" *)
  reg [6:0] count_bit;
  (* src = "transmitter_SPI.v:32.18-32.25" *)
  input [15:0] data_in;
  wire [15:0] data_in;
  (* src = "transmitter_SPI.v:49.24-49.32" *)
  reg [1:0] div_freq;
  (* src = "transmitter_SPI.v:50.16-50.26" *)
  reg [15:0] inter_data;
  (* src = "transmitter_SPI.v:57.12-57.23" *)
  wire negedge_sck;
  (* src = "transmitter_SPI.v:48.26-48.38" *)
  wire [6:0] nx_count_bit;
  (* src = "transmitter_SPI.v:50.28-50.41" *)
  wire [15:0] nx_inter_data;
  (* src = "transmitter_SPI.v:47.22-47.30" *)
  wire [2:0] nx_state;
  (* src = "transmitter_SPI.v:51.10-51.21" *)
  wire posedge_sck;
  (* src = "transmitter_SPI.v:31.16-31.19" *)
  input rst;
  wire rst;
  (* src = "transmitter_SPI.v:55.9-55.21" *)
  reg sck_anterior;
  (* src = "transmitter_SPI.v:47.15-47.20" *)
  reg [2:0] state;
  (* src = "transmitter_SPI.v:31.31-31.35" *)
  input strt;
  wire strt;
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) div_freq[0] <= 1'h0;
    else div_freq[0] <= _087_[0];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) div_freq[1] <= 1'h0;
    else div_freq[1] <= _088_[1];
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  always @*
    if (!_029_) CS = _000_;
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  always @*
    if (!_039_) MOSI = _001_;
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[0] <= 1'h0;
    else if (_016_) inter_data[0] <= nx_inter_data[0];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[1] <= 1'h0;
    else if (_016_) inter_data[1] <= nx_inter_data[1];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[2] <= 1'h0;
    else if (_016_) inter_data[2] <= nx_inter_data[2];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[3] <= 1'h0;
    else if (_016_) inter_data[3] <= nx_inter_data[3];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[4] <= 1'h0;
    else if (_016_) inter_data[4] <= nx_inter_data[4];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[5] <= 1'h0;
    else if (_016_) inter_data[5] <= nx_inter_data[5];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[6] <= 1'h0;
    else if (_016_) inter_data[6] <= nx_inter_data[6];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[7] <= 1'h0;
    else if (_016_) inter_data[7] <= nx_inter_data[7];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[8] <= 1'h0;
    else if (_016_) inter_data[8] <= nx_inter_data[8];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[9] <= 1'h0;
    else if (_016_) inter_data[9] <= nx_inter_data[9];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[10] <= 1'h0;
    else if (_016_) inter_data[10] <= nx_inter_data[10];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[11] <= 1'h0;
    else if (_016_) inter_data[11] <= nx_inter_data[11];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[12] <= 1'h0;
    else if (_016_) inter_data[12] <= nx_inter_data[12];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[13] <= 1'h0;
    else if (_016_) inter_data[13] <= nx_inter_data[13];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[14] <= 1'h0;
    else if (_016_) inter_data[14] <= nx_inter_data[14];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) inter_data[15] <= 1'h0;
    else if (_016_) inter_data[15] <= nx_inter_data[15];
  (* src = "transmitter_SPI.v:78.5-161.8" *)
  always @*
    if (!_040_) SCK = _002_;
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) sck_anterior <= 1'h0;
    else sck_anterior <= SCK;
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) count_bit[0] <= 1'h0;
    else if (_022_) count_bit[0] <= nx_count_bit[0];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) count_bit[1] <= 1'h0;
    else if (_022_) count_bit[1] <= nx_count_bit[1];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) count_bit[2] <= 1'h0;
    else if (_022_) count_bit[2] <= nx_count_bit[2];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) count_bit[3] <= 1'h0;
    else if (_022_) count_bit[3] <= nx_count_bit[3];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) count_bit[4] <= 1'h0;
    else if (_022_) count_bit[4] <= nx_count_bit[4];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) count_bit[5] <= 1'h0;
    else if (_022_) count_bit[5] <= nx_count_bit[5];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) count_bit[6] <= 1'h0;
    else if (_022_) count_bit[6] <= nx_count_bit[6];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) state[0] <= 1'h0;
    else if (_023_) state[0] <= nx_state[0];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) state[1] <= 1'h0;
    else if (_023_) state[1] <= nx_state[1];
  (* src = "transmitter_SPI.v:60.5-75.8" *)
  always @(posedge clk)
    if (!rst) state[2] <= 1'h0;
    else if (_023_) state[2] <= nx_state[2];
  assign _085_[0] = ~count_bit[0];
  assign _045_ = ~state[1];
  assign _046_ = ~_005_[5];
  assign _047_ = ~_005_[4];
  assign _048_ = ~state[0];
  assign _087_[0] = ~div_freq[0];
  assign _028_ = ~negedge_sck;
  assign _026_ = ~CPH;
  assign _049_[0] = _065_[0] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _065_[1];
  assign _049_[1] = _065_[2] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _065_[3];
  assign _049_[2] = _065_[4] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _065_[5];
  assign _049_[3] = _065_[6] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _065_[7];
  assign _049_[4] = _065_[8] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _065_[9];
  assign _049_[5] = _065_[10] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _065_[11];
  assign _049_[6] = _065_[12] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _065_[13];
  assign _049_[7] = _065_[14] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _065_[15];
  assign _050_[0] = _049_[0] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _049_[1];
  assign _050_[1] = _049_[2] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _049_[3];
  assign _050_[2] = _049_[4] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _049_[5];
  assign _050_[3] = _049_[6] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _049_[7];
  assign _051_[0] = _050_[0] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _050_[1];
  assign _051_[1] = _050_[2] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _050_[3];
  assign _068_ = _051_[0] |(* src = "transmitter_SPI.v:144.29-144.53" *)  _051_[1];
  assign _052_[0] = _085_[0] |(* src = "transmitter_SPI.v:144.57-144.71" *)  count_bit[1];
  assign _052_[1] = count_bit[2] |(* src = "transmitter_SPI.v:144.57-144.71" *)  count_bit[3];
  assign _052_[2] = count_bit[4] |(* src = "transmitter_SPI.v:144.57-144.71" *)  count_bit[5];
  assign _053_[0] = _052_[0] |(* src = "transmitter_SPI.v:144.57-144.71" *)  _052_[1];
  assign _053_[1] = _052_[2] |(* src = "transmitter_SPI.v:144.57-144.71" *)  count_bit[6];
  assign _073_ = _053_[0] |(* src = "transmitter_SPI.v:144.57-144.71" *)  _053_[1];
  assign _054_[0] = _005_[0] |(* src = "transmitter_SPI.v:155.26-155.44" *)  _005_[1];
  assign _054_[1] = _005_[2] |(* src = "transmitter_SPI.v:155.26-155.44" *)  _005_[3];
  assign _054_[2] = _047_ |(* src = "transmitter_SPI.v:155.26-155.44" *)  _046_;
  assign _055_[0] = _054_[0] |(* src = "transmitter_SPI.v:155.26-155.44" *)  _054_[1];
  assign _055_[1] = _054_[2] |(* src = "transmitter_SPI.v:155.26-155.44" *)  _005_[6];
  assign _069_ = _055_[0] |(* src = "transmitter_SPI.v:155.26-155.44" *)  _055_[1];
  assign _056_ = _048_ |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *)  state[1];
  assign _000_ = _056_ |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *)  state[2];
  assign _057_ = state[0] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *)  _045_;
  assign _025_ = _057_ |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *)  state[2];
  assign _032_ = CPH |(* src = "transmitter_SPI.v:78.5-161.8" *)  _041_;
  assign _037_ = _042_ |(* src = "transmitter_SPI.v:78.5-161.8" *)  _043_;
  assign _039_ = _025_ |(* src = "transmitter_SPI.v:78.5-161.8" *)  _044_;
  assign _022_ = _077_[0] | _077_[2];
  assign _058_[0] = _021_ & _020_;
  assign _058_[1] = _019_ & _018_;
  assign _059_ = _058_[0] & _058_[1];
  assign _023_ = _059_ & _017_;
  assign _021_ = _016_ | _077_[2];
  assign _020_ = strt | _024_;
  assign _060_[0] = _026_ | _028_;
  assign _060_[1] = _066_[2] | _025_;
  assign _019_ = _060_[0] | _060_[1];
  assign _061_ = _026_ | negedge_sck;
  assign _018_ = _061_ | _025_;
  assign _062_ = CPH | _067_[1];
  assign _017_ = _062_ | _025_;
  assign _078_[2] = _076_[2] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _076_[8];
  assign _063_ = _076_[2] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _076_[4];
  assign _078_[1] = _063_ |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _076_[8];
  assign _078_[0] = _076_[2] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _076_[6];
  assign _016_ = _077_[0] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _076_[4];
  assign _083_[15] = _082_[15] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[31];
  assign _083_[14] = _082_[14] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[30];
  assign _083_[13] = _082_[13] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[29];
  assign _083_[12] = _082_[12] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[28];
  assign _083_[11] = _082_[11] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[27];
  assign _083_[10] = _082_[10] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[26];
  assign _083_[9] = _082_[9] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[25];
  assign _083_[8] = _082_[8] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[24];
  assign _083_[7] = _082_[7] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[23];
  assign _083_[6] = _082_[6] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[22];
  assign _083_[5] = _082_[5] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[21];
  assign _083_[4] = _082_[4] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[20];
  assign _083_[3] = _082_[3] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[19];
  assign _083_[2] = _082_[2] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[18];
  assign _083_[1] = _082_[1] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[17];
  assign _083_[0] = _082_[0] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _082_[16];
  assign _064_ = state[0] |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *)  state[1];
  assign _024_ = _064_ |(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *)  state[2];
  assign _071_ = ~(* src = "transmitter_SPI.v:56.26-56.39" *) sck_anterior;
  assign _072_ = ~(* src = "transmitter_SPI.v:57.42-57.46" *) SCK;
  assign _070_ = ~(* src = "transmitter_SPI.v:144.29-144.53" *) _068_;
  assign _067_[1] = ~(* src = "transmitter_SPI.v:155.26-155.44" *) _069_;
  assign _077_[2] = ~(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) _024_;
  assign _076_[4] = ~(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) _000_;
  assign _077_[0] = ~(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) _025_;
  assign posedge_sck = _071_ &(* src = "transmitter_SPI.v:56.26-56.46" *)  SCK;
  assign negedge_sck = sck_anterior &(* src = "transmitter_SPI.v:57.26-57.46" *)  _072_;
  assign _066_[2] = _070_ &(* src = "transmitter_SPI.v:144.29-144.71" *)  _073_;
  assign nx_inter_data[0] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[0] : 1'hx;
  assign nx_inter_data[1] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[1] : 1'hx;
  assign nx_inter_data[2] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[2] : 1'hx;
  assign nx_inter_data[3] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[3] : 1'hx;
  assign nx_inter_data[4] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[4] : 1'hx;
  assign nx_inter_data[5] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[5] : 1'hx;
  assign nx_inter_data[6] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[6] : 1'hx;
  assign nx_inter_data[7] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[7] : 1'hx;
  assign nx_inter_data[8] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[8] : 1'hx;
  assign nx_inter_data[9] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[9] : 1'hx;
  assign nx_inter_data[10] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[10] : 1'hx;
  assign nx_inter_data[11] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[11] : 1'hx;
  assign nx_inter_data[12] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[12] : 1'hx;
  assign nx_inter_data[13] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[13] : 1'hx;
  assign nx_inter_data[14] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[14] : 1'hx;
  assign nx_inter_data[15] = _016_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[15] : 1'hx;
  assign _015_[2] = _069_ ? (* src = "transmitter_SPI.v:155.26-155.44|transmitter_SPI.v:155.22-155.65" *) 1'hx : 1'h0;
  assign _014_[2] = _066_[2] ? (* src = "transmitter_SPI.v:144.29-144.71|transmitter_SPI.v:144.25-144.92" *) 1'h0 : 1'hx;
  assign _013_[2] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) _014_[2] : 1'hx;
  assign _011_[0] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) _085_[0] : _005_[0];
  assign _011_[1] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) _086_[1] : _005_[1];
  assign _011_[2] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) _086_[2] : _005_[2];
  assign _011_[3] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) _086_[3] : _005_[3];
  assign _011_[4] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) _086_[4] : _005_[4];
  assign _011_[5] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) _086_[5] : _005_[5];
  assign _011_[6] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) _086_[6] : _005_[6];
  assign _012_[0] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[1] : _006_[0];
  assign _012_[1] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[2] : _006_[1];
  assign _012_[2] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[3] : _006_[2];
  assign _012_[3] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[4] : _006_[3];
  assign _012_[4] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[5] : _006_[4];
  assign _012_[5] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[6] : _006_[5];
  assign _012_[6] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[7] : _006_[6];
  assign _012_[7] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[8] : _006_[7];
  assign _012_[8] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[9] : _006_[8];
  assign _012_[9] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[10] : _006_[9];
  assign _012_[10] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[11] : _006_[10];
  assign _012_[11] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[12] : _006_[11];
  assign _012_[12] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[13] : _006_[12];
  assign _012_[13] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[14] : _006_[13];
  assign _012_[14] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[15] : _006_[14];
  assign _012_[15] = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) MISO : _006_[15];
  assign _010_ = negedge_sck ? (* src = "transmitter_SPI.v:140.25-140.36|transmitter_SPI.v:140.21-145.24" *) inter_data[0] : _003_;
  assign _081_[0] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[0] : _006_[0];
  assign _081_[1] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[1] : _006_[1];
  assign _081_[2] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[2] : _006_[2];
  assign _081_[3] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[3] : _006_[3];
  assign _081_[4] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[4] : _006_[4];
  assign _081_[5] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[5] : _006_[5];
  assign _081_[6] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[6] : _006_[6];
  assign _081_[7] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[7] : _006_[7];
  assign _081_[8] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[8] : _006_[8];
  assign _081_[9] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[9] : _006_[9];
  assign _081_[10] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[10] : _006_[10];
  assign _081_[11] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[11] : _006_[11];
  assign _081_[12] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[12] : _006_[12];
  assign _081_[13] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[13] : _006_[13];
  assign _081_[14] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[14] : _006_[14];
  assign _081_[15] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _012_[15] : _006_[15];
  assign _079_[0] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _011_[0] : _005_[0];
  assign _079_[1] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _011_[1] : _005_[1];
  assign _079_[2] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _011_[2] : _005_[2];
  assign _079_[3] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _011_[3] : _005_[3];
  assign _079_[4] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _011_[4] : _005_[4];
  assign _079_[5] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _011_[5] : _005_[5];
  assign _079_[6] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _011_[6] : _005_[6];
  assign _075_[2] = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _013_[2] : _015_[2];
  assign _001_ = CPH ? (* src = "transmitter_SPI.v:139.21-139.24|transmitter_SPI.v:139.17-155.65" *) _010_ : _003_;
  assign _008_[0] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) _085_[0] : count_bit[0];
  assign _008_[1] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) _086_[1] : count_bit[1];
  assign _008_[2] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) _086_[2] : count_bit[2];
  assign _008_[3] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) _086_[3] : count_bit[3];
  assign _008_[4] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) _086_[4] : count_bit[4];
  assign _008_[5] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) _086_[5] : count_bit[5];
  assign _008_[6] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) _086_[6] : count_bit[6];
  assign _009_[0] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[1] : inter_data[0];
  assign _009_[1] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[2] : inter_data[1];
  assign _009_[2] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[3] : inter_data[2];
  assign _009_[3] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[4] : inter_data[3];
  assign _009_[4] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[5] : inter_data[4];
  assign _009_[5] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[6] : inter_data[5];
  assign _009_[6] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[7] : inter_data[6];
  assign _009_[7] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[8] : inter_data[7];
  assign _009_[8] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[9] : inter_data[8];
  assign _009_[9] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[10] : inter_data[9];
  assign _009_[10] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[11] : inter_data[10];
  assign _009_[11] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[12] : inter_data[11];
  assign _009_[12] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[13] : inter_data[12];
  assign _009_[13] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[14] : inter_data[13];
  assign _009_[14] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[15] : inter_data[14];
  assign _009_[15] = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) MISO : inter_data[15];
  assign _007_ = posedge_sck ? (* src = "transmitter_SPI.v:125.25-125.36|transmitter_SPI.v:125.21-129.24" *) inter_data[0] : MOSI;
  assign _006_[0] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[0] : _009_[0];
  assign _006_[1] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[1] : _009_[1];
  assign _006_[2] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[2] : _009_[2];
  assign _006_[3] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[3] : _009_[3];
  assign _006_[4] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[4] : _009_[4];
  assign _006_[5] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[5] : _009_[5];
  assign _006_[6] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[6] : _009_[6];
  assign _006_[7] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[7] : _009_[7];
  assign _006_[8] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[8] : _009_[8];
  assign _006_[9] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[9] : _009_[9];
  assign _006_[10] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[10] : _009_[10];
  assign _006_[11] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[11] : _009_[11];
  assign _006_[12] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[12] : _009_[12];
  assign _006_[13] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[13] : _009_[13];
  assign _006_[14] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[14] : _009_[14];
  assign _006_[15] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) inter_data[15] : _009_[15];
  assign _074_[0] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) count_bit[0] : _008_[0];
  assign _074_[1] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) count_bit[1] : _008_[1];
  assign _074_[2] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) count_bit[2] : _008_[2];
  assign _074_[3] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) count_bit[3] : _008_[3];
  assign _074_[4] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) count_bit[4] : _008_[4];
  assign _074_[5] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) count_bit[5] : _008_[5];
  assign _074_[6] = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) count_bit[6] : _008_[6];
  assign _005_[0] = _025_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) 1'hx : _074_[0];
  assign _005_[1] = _025_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) 1'hx : _074_[1];
  assign _005_[2] = _025_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) 1'hx : _074_[2];
  assign _005_[3] = _025_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) 1'hx : _074_[3];
  assign _005_[4] = _025_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) 1'hx : _074_[4];
  assign _005_[5] = _025_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) 1'hx : _074_[5];
  assign _005_[6] = _025_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) 1'hx : _074_[6];
  assign _003_ = CPH ? (* src = "transmitter_SPI.v:124.21-124.25|transmitter_SPI.v:124.17-136.20" *) MOSI : _007_;
  assign _004_ = ~(* src = "transmitter_SPI.v:108.21-108.24|transmitter_SPI.v:108.17-115.20" *) CKP;
  assign _075_[6] = strt ? (* src = "transmitter_SPI.v:95.21-95.25|transmitter_SPI.v:95.17-95.44" *) 1'h1 : 1'hx;
  assign _075_[8] = strt ? (* src = "transmitter_SPI.v:95.21-95.25|transmitter_SPI.v:95.17-95.44" *) 1'h0 : 1'hx;
  assign _002_ = _025_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16" *) _004_ : div_freq[1];
  assign nx_state[0] = _021_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _078_[0] : 1'hx;
  assign nx_state[1] = _021_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _078_[1] : 1'hx;
  assign nx_state[2] = _021_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _078_[2] : 1'hx;
  assign nx_count_bit[0] = _022_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _080_[0] : 1'hx;
  assign nx_count_bit[1] = _022_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _080_[1] : 1'hx;
  assign nx_count_bit[2] = _022_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _080_[2] : 1'hx;
  assign nx_count_bit[3] = _022_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _080_[3] : 1'hx;
  assign nx_count_bit[4] = _022_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _080_[4] : 1'hx;
  assign nx_count_bit[5] = _022_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _080_[5] : 1'hx;
  assign nx_count_bit[6] = _022_ ? (* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _080_[6] : 1'hx;
  assign _027_ = ~(* src = "transmitter_SPI.v:78.5-161.8" *) posedge_sck;
  assign _082_[17] = data_in[1] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[18] = data_in[2] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[19] = data_in[3] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[20] = data_in[4] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[21] = data_in[5] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[22] = data_in[6] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[23] = data_in[7] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[24] = data_in[8] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[25] = data_in[9] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[26] = data_in[10] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[27] = data_in[11] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[28] = data_in[12] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[29] = data_in[13] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[30] = data_in[14] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[31] = data_in[15] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _082_[0] = _081_[0] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[1] = _081_[1] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[2] = _081_[2] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[3] = _081_[3] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[4] = _081_[4] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[5] = _081_[5] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[6] = _081_[6] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[7] = _081_[7] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[8] = _081_[8] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[9] = _081_[9] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[10] = _081_[10] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[11] = _081_[11] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[12] = _081_[12] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[13] = _081_[13] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[14] = _081_[14] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[15] = _081_[15] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _088_[1] = div_freq[1] ^(* src = "transmitter_SPI.v:70.29-70.39|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  div_freq[0];
  assign _086_[1] = count_bit[1] ^(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  count_bit[0];
  assign _086_[2] = count_bit[2] ^(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _084_[1];
  assign _086_[3] = count_bit[3] ^(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _084_[2];
  assign _086_[4] = count_bit[4] ^(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _084_[3];
  assign _086_[5] = count_bit[5] ^(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _084_[4];
  assign _086_[6] = count_bit[6] ^(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _084_[5];
  assign _084_[1] = count_bit[1] &(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  count_bit[0];
  assign _084_[3] = _089_ &(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _084_[1];
  assign _089_ = count_bit[3] &(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count_bit[2];
  assign _090_ = count_bit[5] &(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  count_bit[4];
  assign _084_[5] = _090_ &(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _084_[3];
  assign _084_[2] = count_bit[2] &(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _084_[1];
  assign _084_[4] = count_bit[4] &(* src = "transmitter_SPI.v:143.40-143.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _084_[3];
  assign _065_[0] = inter_data[1] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[0];
  assign _065_[1] = inter_data[2] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[1];
  assign _065_[2] = inter_data[3] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[2];
  assign _065_[3] = inter_data[4] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[3];
  assign _065_[4] = inter_data[5] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[4];
  assign _065_[5] = inter_data[6] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[5];
  assign _065_[6] = inter_data[7] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[6];
  assign _065_[7] = inter_data[8] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[7];
  assign _065_[8] = inter_data[9] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[8];
  assign _065_[9] = inter_data[10] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[9];
  assign _065_[10] = inter_data[11] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[10];
  assign _065_[11] = inter_data[12] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[11];
  assign _065_[12] = inter_data[13] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[12];
  assign _065_[13] = inter_data[14] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[13];
  assign _065_[14] = inter_data[15] ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[14];
  assign _065_[15] = MISO ^(* src = "transmitter_SPI.v:144.29-144.53" *)  data_in[15];
  assign _029_ = _024_ &(* src = "transmitter_SPI.v:78.5-161.8" *)  _000_;
  assign _030_ = _026_ &(* src = "transmitter_SPI.v:78.5-161.8" *)  _027_;
  assign _031_ = _077_[0] &(* src = "transmitter_SPI.v:78.5-161.8" *)  _030_;
  assign _041_ = _026_ &(* src = "transmitter_SPI.v:78.5-161.8" *)  _031_;
  assign _033_ = _077_[0] &(* src = "transmitter_SPI.v:78.5-161.8" *)  _032_;
  assign _042_ = _026_ &(* src = "transmitter_SPI.v:78.5-161.8" *)  _033_;
  assign _034_ = _028_ &(* src = "transmitter_SPI.v:78.5-161.8" *)  _033_;
  assign _035_ = CPH &(* src = "transmitter_SPI.v:78.5-161.8" *)  _034_;
  assign _036_ = _077_[0] &(* src = "transmitter_SPI.v:78.5-161.8" *)  _035_;
  assign _043_ = CPH &(* src = "transmitter_SPI.v:78.5-161.8" *)  _036_;
  assign _038_ = _077_[0] &(* src = "transmitter_SPI.v:78.5-161.8" *)  _037_;
  assign _044_ = _077_[0] &(* src = "transmitter_SPI.v:78.5-161.8" *)  _038_;
  assign _040_ = _000_ &(* src = "transmitter_SPI.v:78.5-161.8" *)  _025_;
  assign _076_[6] = _075_[6] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[2];
  assign _076_[8] = _075_[8] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[2];
  assign _076_[2] = _075_[2] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _080_[0] = _079_[0] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _080_[1] = _079_[1] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _080_[2] = _079_[2] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _080_[3] = _079_[3] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _080_[4] = _079_[4] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _080_[5] = _079_[5] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _080_[6] = _079_[6] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _077_[0];
  assign _082_[16] = data_in[0] &(* src = "transmitter_SPI.v:0.0-0.0|transmitter_SPI.v:91.9-159.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _076_[4];
  assign _013_[1:0] = { _013_[2], _013_[2] };
  assign _014_[1:0] = { _014_[2], _014_[2] };
  assign _015_[1:0] = { _015_[2], _015_[2] };
  assign { _066_[3], _066_[1:0] } = { _025_, _028_, _026_ };
  assign { _067_[2], _067_[0] } = { _025_, CPH };
  assign { _075_[7], _075_[5:3], _075_[1:0] } = { _075_[8], 3'h2, _075_[2], _075_[2] };
  assign { _076_[7], _076_[5], _076_[3], _076_[1:0] } = { _076_[8], 2'h0, _076_[2], _076_[2] };
  assign _077_[1] = _076_[4];
  assign _079_[13:7] = 7'h00;
  assign _080_[13:7] = 7'h00;
  assign _081_[31:16] = data_in;
  assign { _084_[31:7], _084_[0] } = { 25'h0000000, count_bit[0] };
  assign _085_[31:1] = { 25'h0000000, count_bit[6:1] };
  assign { _086_[31:7], _086_[0] } = { 24'h000000, _084_[6], _085_[0] };
  assign _087_[31:1] = { 30'h00000000, div_freq[1] };
  assign { _088_[31:3], _088_[0] } = { 29'h00000000, _087_[0] };
endmodule
